name: CI/CD Release Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop

env:
  TARGETARCH: amd64
  TARGETOS: linux
  CGO_ENABLED: 0
  VALUES_FILEPATH: helm/values.yaml
  REGISTRY: ghcr.io/kseniiaevans


jobs:
  ci:
    name: CI - Build and Push
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set VERSION
        id: version
        run: |
          VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "📦 Building version: ${VERSION}"
      
      - name: Run tests
        run: make test
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and Push Docker Image
        run: |
          make image push \
            TARGETARCH=${{ env.TARGETARCH }} \
            TARGETOS=${{ env.TARGETOS }} \
            VERSION=${{ env.VERSION }} \
            REGISTRY=${{ env.REGISTRY }}
          echo "Image pushed: ${{ env.REGISTRY }}/kbot:${{ env.VERSION }}-${{ env.TARGETOS }}-${{ env.TARGETARCH }}"

  cd:
    name: CD - Update Helm Chart
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set VERSION
        run: echo "VERSION=${{ needs.ci.outputs.version }}" >> $GITHUB_ENV
      
      - name: Update Helm values.yaml
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.image.tag = strenv(VERSION)' ${{ env.VALUES_FILEPATH }}
      
      - name: Commit and Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ env.VALUES_FILEPATH }}
        
          git commit -m "chore: update image tag to ${{ env.VERSION }} [skip ci]"
          git push
          echo "✅ Helm chart updated with version ${{ env.VERSION }}"

      - name: Cleanup Docker
        run: |
          echo "🧹 Cleaning up..."
          make clean \
            TARGETARCH=${{ env.TARGETARCH }} \
            TARGETOS=${{ env.TARGETOS }} \
            VERSION=${{ env.VERSION }} \
            REGISTRY=${{ env.REGISTRY }}
          docker system prune -af || true